### PR TITLE
Fix missing foldl' import in Automaton.hs (regression in 2.1.1.0)

### PR DESCRIPTION
**Pull request by Unisay**
## Summary

`foldl'` was explicitly imported from `Data.Foldable` in `2.1.0.2` but this import was accidentally dropped in `2.1.1.0`. The call site at line ~292 uses it unqualified, which fails to compile on GHC 9.6 where `foldl'` is not re-exported via `Prelude` and `Data.List` is only in scope as `qualified ... as List`.

## Affected versions

- `2.1.1.0` — broken on GHC 9.6 (e.g. aarch64-linux)
- `2.1.0.2` — worked (had `import Data.Foldable (foldl')`)

## Fix

Add back the missing import:

```haskell
import Data.Foldable (foldl')
```

## Error observed

```
src/Data/Text/AhoCorasick/Automaton.hs:292:5: error:
    Variable not in scope: foldl'
    Suggested fix: use 'IntMap.foldl'' or 'Vector.foldl'' or 'Text.foldl''
```

### CODE REVIEW

**Comment by ReinierMaas** [comment]
Thanks for notifying us! We indeed now test with `GHC9.14` and have missed this regression for `GHC9.6`.

**Comment by ReinierMaas** [comment]
XRef: 2f8fc08d2654c07804b2ea3f4c1e427dcf44e0db

In order to prevent backwards incompatible breakage and remove the warnings that are generated by the latest compilers I have opted to use the `foldl'` from `List` instead.

**Comment by erikd** [comment]
Looking forward to this being merged and a fix being release to Hackage.

**Comment by ReinierMaas** [comment]
We have heard you! The fix and running GHC matrix (multiple different compiler versions) landed last week.

* https://github.com/channable/alfred-margaret/pull/77

The release wasn't (yet) cut and uploaded to Hackage. I will be the release manager again.

* https://github.com/channable/alfred-margaret/pull/78
* https://github.com/channable/alfred-margaret/releases/tag/v2.1.1.1

**Comment by ReinierMaas** [comment]
The release is now available on Hackage: https://hackage.haskell.org/package/alfred-margaret-2.1.1.1
